server:
  port: 8081

spring:
  profiles:
    active: dev
  redis:
    host: ${hmdp.redis.host}
    port: ${hmdp.redis.port}
    password: ${hmdp.redis.password}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: ${hmdp.redis.database}
  datasource:
    driver-class-name: ${hmdp.datasource.driver-class-name}
    url: jdbc:mysql://${hmdp.datasource.host}:${hmdp.datasource.port}/${hmdp.datasource.database}?useSSL=false&serverTimezone=UTC
    username: ${hmdp.datasource.username}
    password: ${hmdp.datasource.password}

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包

logging:
  level:
    com:
      hmdp:
        mapper: debug
        service: info
        controller: info

