hmdp:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    host: localhost
    port: 3306
    database: hmdp
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1